[2014-05-29 17:00:41.682505]
ERROR
	Peer will receive following PB traceback:
[2014-05-29 17:00:41.752805]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 153, in gotItem
    self.callExpressionReceived(item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 116, in callExpressionReceived
    self.expressionReceived(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 565, in expressionReceived
    method(*sexp[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 877, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/distributed/reference.py", line 25, in remote_callChild
    return self._service.callTarget(command,*arg,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 84, in callTarget
    result = self.callTargetSingle(targetKey,*args,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 104, in callTargetSingle
    defer_data = target(*args,**kw)
  File "/Users/Psyko/Desktop/Soccer/app/game/gatenodeapp/player.py", line 102, in dissmissPlayer_409
    response=player.DissmissPlayer(dynamic,characterId,playerId)
  File "/Users/Psyko/Desktop/Soccer/app/game/appinterface/player.py", line 111, in DissmissPlayer
    playerquality=player.level.getPlayerQuality()
exceptions.AttributeError: 'NoneType' object has no attribute 'level'

[2014-05-29 17:00:47.723623]
ERROR
	Peer will receive following PB traceback:
[2014-05-29 17:00:47.724492]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 153, in gotItem
    self.callExpressionReceived(item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 116, in callExpressionReceived
    self.expressionReceived(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 565, in expressionReceived
    method(*sexp[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 877, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/distributed/reference.py", line 25, in remote_callChild
    return self._service.callTarget(command,*arg,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 84, in callTarget
    result = self.callTargetSingle(targetKey,*args,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 104, in callTargetSingle
    defer_data = target(*args,**kw)
  File "/Users/Psyko/Desktop/Soccer/app/game/gatenodeapp/player.py", line 102, in dissmissPlayer_409
    response=player.DissmissPlayer(dynamic,characterId,playerId)
  File "/Users/Psyko/Desktop/Soccer/app/game/appinterface/player.py", line 111, in DissmissPlayer
    playerquality=player.level.getPlayerQuality()
exceptions.AttributeError: 'NoneType' object has no attribute 'level'

[2014-05-29 17:00:48.542850]
ERROR
	Peer will receive following PB traceback:
[2014-05-29 17:00:48.543729]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 153, in gotItem
    self.callExpressionReceived(item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 116, in callExpressionReceived
    self.expressionReceived(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 565, in expressionReceived
    method(*sexp[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 877, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/distributed/reference.py", line 25, in remote_callChild
    return self._service.callTarget(command,*arg,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 84, in callTarget
    result = self.callTargetSingle(targetKey,*args,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 104, in callTargetSingle
    defer_data = target(*args,**kw)
  File "/Users/Psyko/Desktop/Soccer/app/game/gatenodeapp/player.py", line 102, in dissmissPlayer_409
    response=player.DissmissPlayer(dynamic,characterId,playerId)
  File "/Users/Psyko/Desktop/Soccer/app/game/appinterface/player.py", line 111, in DissmissPlayer
    playerquality=player.level.getPlayerQuality()
exceptions.AttributeError: 'NoneType' object has no attribute 'level'

[2014-05-29 17:00:48.952384]
ERROR
	Peer will receive following PB traceback:
[2014-05-29 17:00:48.953164]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 153, in gotItem
    self.callExpressionReceived(item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 116, in callExpressionReceived
    self.expressionReceived(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 565, in expressionReceived
    method(*sexp[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 877, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/distributed/reference.py", line 25, in remote_callChild
    return self._service.callTarget(command,*arg,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 84, in callTarget
    result = self.callTargetSingle(targetKey,*args,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 104, in callTargetSingle
    defer_data = target(*args,**kw)
  File "/Users/Psyko/Desktop/Soccer/app/game/gatenodeapp/player.py", line 102, in dissmissPlayer_409
    response=player.DissmissPlayer(dynamic,characterId,playerId)
  File "/Users/Psyko/Desktop/Soccer/app/game/appinterface/player.py", line 111, in DissmissPlayer
    playerquality=player.level.getPlayerQuality()
exceptions.AttributeError: 'NoneType' object has no attribute 'level'

[2014-05-29 17:01:59.406152]
ERROR
	Peer will receive following PB traceback:
[2014-05-29 17:01:59.407076]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 153, in gotItem
    self.callExpressionReceived(item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/banana.py", line 116, in callExpressionReceived
    self.expressionReceived(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 565, in expressionReceived
    method(*sexp[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 877, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/distributed/reference.py", line 25, in remote_callChild
    return self._service.callTarget(command,*arg,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 84, in callTarget
    result = self.callTargetSingle(targetKey,*args,**kw)
  File "/Library/Python/2.7/site-packages/firefly-1.3.2dev-py2.7.egg/firefly/utils/services.py", line 104, in callTargetSingle
    defer_data = target(*args,**kw)
  File "/Users/Psyko/Desktop/Soccer/app/game/gatenodeapp/player.py", line 102, in dissmissPlayer_409
    response=player.DissmissPlayer(dynamic,characterId,playerId)
  File "/Users/Psyko/Desktop/Soccer/app/game/appinterface/player.py", line 111, in DissmissPlayer
    playerquality=player.level.getPlayerQuality()
exceptions.AttributeError: 'NoneType' object has no attribute 'level'

